version: '3.7'

x-broker_db_dependencies:
  &broker_db_dependencies
  depends_on:
    db:
      condition: service_started
    rabbitmq:
      condition: service_healthy

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/etc/:/etc/rabbitmq/
      - ./rabbitmq/data:/var/lib/rabbitmq
    healthcheck:
      test: nc -z localhost:5672

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres:13.3
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:80"
    << : *broker_db_dependencies
    volumes:
      - ./data:/app/data
    env_file:
      - .env

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    deploy:
      replicas: 1
    command: "celery -A tasks worker -l info -Q celery"
    network_mode: host
    << : *broker_db_dependencies
    volumes:
      - ./data:/data
    env_file:
      - .env